security:

    role_hierarchy:
        'ROLE_ADMIN': [ROLE_USER]
    
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        App\Entity\User:
            algorithm: bcrypt
        App\Entity\Student:
            algorithm: bcrypt
        App\Entity\Company:
            algorithm: bcrypt
        App\Entity\Institute:
            algorithm: bcrypt

    
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [ in_memory, db_provider, student_provider, company_provider, institute_provider ]
        in_memory:
            memory:
                users:
                    admin: 
                        password: $2y$13$l.DiQY.bz1bot9vuweebbu4wLgczClqkUPJ1dp2d/rIisAMfK.ECa
                        roles: 'ROLE_ADMIN'
        db_provider:
            entity:
                class: App\Entity\User
                property: username
        student_provider:
            entity:
                class: App\Entity\Student
                property: username
        company_provider:
            entity:
                class: App\Entity\Company
                property: username
        Institute_provider:
            entity:
                class: App\Entity\Institute
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: chain_provider
            form-login: 
                login-path: login
                check-path: login
            logout: true
            anonymous: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #- { path: ^/company, role: ROLE_COMPANY }
        #- { path: ^/institute, role: ROLE_INSTITUTE }
        #- { path: ^/student, role: ROLE_STUDENT }
        #- { path: ^/registration-form-submission$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/(login|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: ROLE_USER }
